export type { DbError, DbErrorKind } from './errors.js';
export { NotFoundError, toDbError } from './errors.js';
export type { Err, Ok, Result } from './result.js';
export { err, isErr, isOk, ok } from './result.js';
export type { Infer, ZodCompat } from './compat/zod.js';
export type { IdStrategy, InferIdType } from './id.js';
export type { IndexDef } from './indexes.js';
export { index, syncIndexes, generateIndexMigration } from './indexes.js';
export type { CollectionDef, Doc } from './collection.js';
export { defineCollection } from './collection.js';
export type { Repository } from './repository.js';
export { createRepository } from './mongo-repository.js';
export type { QueryBuilder } from './query-builder.js';
